export const ANDROID_DARK_FALLBACK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#1a2331' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#c8d2e4' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#111823' }] },
  { featureType: 'administrative', elementType: 'geometry.stroke', stylers: [{ color: '#37465f' }] },
  { featureType: 'administrative.land_parcel', elementType: 'labels.text.fill', stylers: [{ color: '#8ea1bd' }] },
  { featureType: 'landscape.man_made', elementType: 'geometry', stylers: [{ color: '#1b2a39' }] },
  { featureType: 'landscape.natural', elementType: 'geometry', stylers: [{ color: '#1a2f35' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#223142' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#9db0c8' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#1f4d4a' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#31435a' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#1b2735' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#c0ccde' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#3c5680' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#24344b' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#2a3a4f' }] },
  { featureType: 'transit.station', elementType: 'labels.text.fill', stylers: [{ color: '#b4c3da' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#17426f' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#9ebee0' }] },
];
